"""CatWing icon system: registry loader plus every published emitter.

Source of truth:
    icons/registry.json    role -> glyph, category, keywords, never_means
    icons/lucide/*.svg     vendored lucide sources (pinned, never hand-edited)
    icons/custom/*.svg     CatWing domain glyphs drawn on lucide's 24px grid

Emitted into icons/dist/ (gitignored, rebuilt on every build):
    svg/<role>.svg                 one optimized file per role
    sprite.svg                     <symbol> sheet for non-React consumers
    icons.json                     manifest (version, roles, metadata)
    png/<role>-<size>-<theme>.png  raster set, 16/24/32/64 x light/dark
    react/icon-paths.gen.ts        inline-SVG body per role (vendored by catwing)
    react/icon-names.gen.ts        IconName union + ICON_NAMES tuple

PNG rasterisation needs cairosvg (see requirements.txt). Every other emitter is
stdlib-only, so `python tools/build.py --no-open` still succeeds without it.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

BRAND_DIR = Path(__file__).resolve().parents[1]
ICONS_DIR = BRAND_DIR / "icons"
REGISTRY_PATH = ICONS_DIR / "registry.json"
DIST_DIR = ICONS_DIR / "dist"

PNG_SIZES = (16, 24, 32, 64)
PNG_THEMES = {"light": "#0F172A", "dark": "#F8FAFC"}

_SVG_BODY = re.compile(r"<svg[^>]*>(.*)</svg>", re.DOTALL)
_GENERATED_HEADER = (
    "// GENERATED by catwing-brand tools/icons.py — DO NOT EDIT.\n"
    "// Source: catwing-brand icons/registry.json @ version {version}\n"
    "// Re-vendor by copying icons/dist/react/ after bumping the brand VERSION.\n"
)


class IconRegistryError(RuntimeError):
    """Raised when the registry and the glyph files disagree."""


def load_registry() -> dict:
    """Read registry.json and fail loudly on any contract breach."""
    registry = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    roles = registry["roles"]
    if not roles:
        raise IconRegistryError("registry.json has no roles")

    seen_glyphs: dict[str, str] = {}
    for role, meta in roles.items():
        for field in ("glyph", "source", "category", "keywords", "never_means"):
            if not meta.get(field):
                raise IconRegistryError(f"{role}: missing {field}")
        source = ICONS_DIR / meta["source"]
        if not source.is_file():
            raise IconRegistryError(f"{role}: {meta['source']} does not exist")
        owner = seen_glyphs.get(meta["glyph"])
        if owner:
            raise IconRegistryError(
                f"glyph {meta['glyph']} claimed by both {owner} and {role} — "
                "one glyph carries exactly one meaning"
            )
        seen_glyphs[meta["glyph"]] = role
    return registry


def glyph_body(meta: dict) -> str:
    """Return the inner markup of a glyph file, whitespace-collapsed."""
    raw = (ICONS_DIR / meta["source"]).read_text(encoding="utf-8")
    match = _SVG_BODY.search(raw)
    if not match:
        raise IconRegistryError(f"{meta['source']} has no <svg> element")
    return re.sub(r"\s+", " ", match.group(1)).strip()


def _standalone_svg(body: str) -> str:
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" '
        'fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" '
        f'stroke-linejoin="round">{body}</svg>\n'
    )


def emit_svg_files(registry: dict, bodies: dict[str, str]) -> Path:
    out = DIST_DIR / "svg"
    out.mkdir(parents=True, exist_ok=True)
    for role, meta in registry["roles"].items():
        (out / f"{meta['glyph']}.svg").write_text(_standalone_svg(bodies[role]), encoding="utf-8")
    return out


def emit_sprite(registry: dict, bodies: dict[str, str]) -> Path:
    symbols = "".join(
        f'<symbol id="cw-icon-{meta["glyph"]}" viewBox="0 0 24 24">{bodies[role]}</symbol>'
        for role, meta in registry["roles"].items()
    )
    sprite = (
        '<svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" '
        'stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="display:none">'
        f"{symbols}</svg>\n"
    )
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    path = DIST_DIR / "sprite.svg"
    path.write_text(sprite, encoding="utf-8")
    return path


def emit_manifest(registry: dict) -> Path:
    manifest = {
        "version": registry["version"],
        "lucide_version": registry["lucide_version"],
        "count": len(registry["roles"]),
        "roles": registry["roles"],
    }
    DIST_DIR.mkdir(parents=True, exist_ok=True)
    path = DIST_DIR / "icons.json"
    path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    return path


def emit_react(registry: dict, bodies: dict[str, str]) -> Path:
    out = DIST_DIR / "react"
    out.mkdir(parents=True, exist_ok=True)
    header = _GENERATED_HEADER.format(version=registry["version"])
    roles = sorted(registry["roles"])

    names = header + "\nexport const ICON_NAMES = [\n"
    names += "".join(f"  '{role}',\n" for role in roles)
    names += "] as const\n\nexport type IconName = (typeof ICON_NAMES)[number]\n"
    (out / "icon-names.gen.ts").write_text(names, encoding="utf-8")

    paths = header + "\nimport type { IconName } from './icon-names.gen'\n\n"
    paths += "export const ICON_PATHS: Record<IconName, string> = {\n"
    for role in roles:
        body = bodies[role].replace("\\", "\\\\").replace("'", "\\'")
        paths += f"  {role}: '{body}',\n"
    paths += "}\n"
    (out / "icon-paths.gen.ts").write_text(paths, encoding="utf-8")
    return out


def emit_png(registry: dict, bodies: dict[str, str]) -> Path | None:
    """Raster set. Returns None (with a warning) when cairosvg is unavailable.

    cairosvg raises OSError at import time when the native cairo library is
    missing — the normal state on a Windows dev box — so both failures degrade
    to a skip. CI installs libcairo2, so the published set is always complete.
    """
    try:
        import cairosvg  # type: ignore[import-not-found]
    except (ImportError, OSError) as exc:
        print(f"  icons: cairosvg unavailable ({type(exc).__name__}) — skipping PNG raster set")
        return None

    out = DIST_DIR / "png"
    out.mkdir(parents=True, exist_ok=True)
    for role, meta in registry["roles"].items():
        for theme, colour in PNG_THEMES.items():
            svg = _standalone_svg(bodies[role]).replace('stroke="currentColor"', f'stroke="{colour}"')
            for size in PNG_SIZES:
                cairosvg.svg2png(
                    bytestring=svg.encode("utf-8"),
                    write_to=str(out / f"{meta['glyph']}-{size}-{theme}.png"),
                    output_width=size,
                    output_height=size,
                )
    return out


def build_all() -> dict:
    """Run every emitter. Called by tools/build.py before page assembly."""
    registry = load_registry()
    bodies = {role: glyph_body(meta) for role, meta in registry["roles"].items()}
    emit_svg_files(registry, bodies)
    emit_sprite(registry, bodies)
    emit_manifest(registry)
    emit_react(registry, bodies)
    emit_png(registry, bodies)
    print(f"  icons: {len(registry['roles'])} roles -> {DIST_DIR.relative_to(BRAND_DIR)}")
    return registry


def _escape(text: str) -> str:
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _never_means_html(note: str) -> str:
    """Render `role` backticks in a never_means note as <code>."""
    return re.sub(r"`([^`]+)`", r"<code>\1</code>", _escape(note))


def gallery_section(registry: dict, bodies: dict[str, str]) -> str:
    """The searchable icon gallery that replaces the old Unicode section."""
    by_category: dict[str, list[str]] = {}
    for role, meta in sorted(registry["roles"].items()):
        by_category.setdefault(meta["category"], []).append(role)

    blocks = []
    for category in sorted(by_category):
        cards = []
        for role in by_category[category]:
            meta = registry["roles"][role]
            cards.append(
                f'<div class="cw-icon-card" data-role="{role}" '
                f'data-keywords="{_escape(" ".join(meta["keywords"]))}">'
                f'<svg class="cw-icon-card-glyph" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
                f'stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
                f"{bodies[role]}</svg>"
                f'<code class="cw-icon-card-name">{role}</code>'
                f'<span class="cw-icon-card-glyphname">{meta["glyph"]}</span>'
                f'<span class="cw-icon-card-note">Never means '
                f'{_never_means_html(meta["never_means"])}</span>'
                "</div>"
            )
        blocks.append(
            f'<h3>{category.title()} <span class="note">({len(by_category[category])})</span></h3>'
            f'<div class="cw-icon-grid">{"".join(cards)}</div>'
        )

    return f"""
    <section id="iconography">
      <h2>6. Iconography</h2>

      <p>CatWing ships <strong>{len(registry["roles"])} icons</strong>, each bound to exactly one
      semantic <strong>role</strong>. Roles are the public name; the underlying glyph is an
      implementation detail. A glyph may never carry two meanings &mdash; that is what lets a user
      learn the vocabulary once and read it everywhere.</p>

      <p class="note">Base set: lucide {registry["lucide_version"]} (ISC), plus CatWing domain glyphs
      drawn on the same 24&nbsp;px grid at 2&nbsp;px stroke with round caps and joins.
      Consume from <code>@catwing/icons</code> in React, or
      <code>icons/dist/sprite.svg</code> + <code>icons/dist/icons.json</code> anywhere else.
      Colour is always <code>currentColor</code>.</p>

      <style>
        .cw-icon-search {{ width:100%; max-width:420px; padding:0.45rem 0.7rem; font-size:0.9rem;
          border:1px solid var(--guide-border); border-radius:6px; background:transparent;
          color:var(--guide-text); margin:0.8rem 0 0.4rem; }}
        .cw-icon-grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(190px,1fr));
          gap:0.6rem; margin-bottom:1.4rem; }}
        .cw-icon-card {{ border:1px solid var(--guide-border); border-radius:8px; padding:0.7rem;
          display:flex; flex-direction:column; gap:0.35rem; }}
        .cw-icon-card-glyph {{ width:24px; height:24px; color:var(--guide-text); }}
        .cw-icon-card-name {{ font-size:0.82rem; font-weight:600; color:var(--guide-text); }}
        .cw-icon-card-glyphname {{ font-size:0.72rem; color:var(--guide-text-muted);
          font-family:ui-monospace,SFMono-Regular,Menlo,monospace; }}
        .cw-icon-card-note {{ font-size:0.72rem; line-height:1.35; color:var(--guide-text-muted); }}
      </style>

      <input type="search" class="cw-icon-search" placeholder="Search roles and keywords&hellip;"
             aria-label="Search icons" oninput="cwFilterIcons(this.value)">
      <p class="note cw-icon-empty" hidden>No role matches that search.</p>

      {"".join(blocks)}

      <script>
      function cwFilterIcons(query) {{
        var q = query.trim().toLowerCase();
        var hits = 0;
        document.querySelectorAll('.cw-icon-card').forEach(function (card) {{
          var hay = card.dataset.role.toLowerCase() + ' ' + card.dataset.keywords;
          var show = !q || hay.indexOf(q) !== -1;
          card.hidden = !show;
          if (show) hits++;
        }});
        document.querySelectorAll('#iconography h3').forEach(function (h) {{
          var grid = h.nextElementSibling;
          h.hidden = !grid.querySelector('.cw-icon-card:not([hidden])');
          grid.hidden = h.hidden;
        }});
        document.querySelector('.cw-icon-empty').hidden = hits !== 0;
      }}
      </script>
    </section>"""
